### ISSUE TITLE
Error: WebSocket was closed before the connection was established

### ISSUE THREAD

**Issue by mitchell-merry** [mitchell-merry/src-wrs-bot-v2#25]
```
bot           | node:events:505
bot           |       throw er; // Unhandled 'error' event
bot           |       ^
bot           | 
bot           | Error: WebSocket was closed before the connection was established
bot           |     at WebSocket.close (/usr/app/node_modules/ws/lib/websocket.js:285:14)
bot           |     at WebSocketShard.destroy (/usr/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:728:27)
bot           |     at Timeout.<anonymous> (/usr/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:522:12)
bot           |     at listOnTimeout (node:internal/timers:559:17)
bot           |     at processTimers (node:internal/timers:502:7)
bot           | Emitted 'error' event on WebSocket instance at:
bot           |     at emitErrorAndClose (/usr/app/node_modules/ws/lib/websocket.js:993:13)
bot           |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
bot           | 
bot           | Node.js v17.9.1

```

**Comment by mitchell-merry** [comment]
https://github.com/discordjs/discord.js/issues/7964 seems to be the solution for this

**Comment by mitchell-merry** [comment]
updated to v14, will reopen this if the error re-occurs
