### ISSUE TITLE
Handle unknown member error

### ISSUE THREAD

**Issue by mitchell-merry** [mitchell-merry/src-wrs-bot-v2#45]
```
bot           | [src-ts] Completed GET https://www.speedrun.com/api/v1/leaderboards/yd4jl5de/category/zd36w1rd?var-5lyj94gl=zqoyx951&top=1
bot           | [869351378726846494] [/update] [996816562059218984] :: [Hello Neighbor - PC (Any%)] Found WR holder(s) (sr.c): y8d0ndgx
bot           | [869351378726846494] [/update] [996816562059218984] :: [Hello Neighbor - PC (Any%)] Found WR holder(s) (discord): 611739779226140672
bot           | [869351378726846494] [/update] [996816562059218984] Account(s) should be (discord): 611739779226140672
bot           | DiscordAPIError: Unknown Member
bot           |     at RequestHandler.execute (/usr/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
bot           |     at runMicrotasks (<anonymous>)
bot           |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
bot           |     at async RequestHandler.push (/usr/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
bot           |     at async GuildMemberManager._fetchSingle (/usr/app/node_modules/discord.js/src/managers/GuildMemberManager.js:407:18) {
bot           |   method: 'get',
bot           |   path: '/guilds/869351378726846494/members/611739779226140672',
bot           |   code: 10007,
bot           |   httpStatus: 404,
bot           |   requestData: { json: undefined, files: [] }
bot           | }

```

**Comment by mitchell-merry** [comment]
Solved by #44
